### ISSUE TITLE
Question - How to embed within another library

### ISSUE THREAD

**Issue by asciidisco** [richardassar/pngcrush.js#1]
Hi,

I would like to embed pngcrush as part of a grunt image optimization plugin, which will be downloadable
via npm. Unfortunatly the pngcrush.js isn´t in npm itself, so my question is:

Can i add the pngcrush.js file in my repo (with mentioning its origin of course), or are there any license issues
i should be aware of? Not: The plugin will be released under MIT License.

Regards
Sebastian

**Comment by richardassar** [comment]
Sebastian,

I can package up pngcrush.js as a standalone interface. This would
allow integration within nodejs. This would be a slow solution, and
also be a blocking solution.

A better approach might be to compile the original pngcrush as a node
module, so you'd benefit from the speed-up there since it would run
the original C source. The source would have to be modified to
input/output the necessary image files (instead of loading them from
disk specified via command line arguments). Also some threading would
have to be put in place to allow a non-blocking solution.

Another approach might be just to invoke the original pngcrush binary
from within node (exec a shell command). That would mean saving and
loading images from disk, making sure the output filenames dont clash.
This would inherently be a non-blocking solution since
child_process.exec is async.

pngcrush is under the libpng licence
http://www.libpng.org/pub/png/src/libpng-LICENSE.txt

Regards,

Richard.

On 29 June 2012 17:19, Sebastian Golasch
reply@reply.github.com
wrote:

**Comment by asciidisco** [comment]
Hey,

first of all, thank you for your quick & detailed answer.
I actually use the pngcrush (or various other png optimize tools), if they are available on the global path.
pngcrush.js just seems like a good fallback solution if the user has none if it installed.

My first intention was to build a node module for pngcrush, but i don´t want to force the user to have
libpng installed, when downloading my library from npm.

I´am totally aware of the fact, that pngcrush.js is slow & blocking, but thats fine,
so if you could package it, that would be super awesome.

Btw.: I tried to run pngmin.js in my shell like so:

``` shell
node pngcrush.js input.png output.png
```

but it only outputs

``` shell
 | pngcrush 1.7.27
 |    Copyright (C) 1998-2002,2006-2012 Glenn Randers-Pehrson
 |    Portions copyright (C) 2005       Greg Roelofs
 | This is a free, open-source program.  Permission is irrevocably
 | granted to everyone to use this version of pngcrush without
 | payment of any fee.
 | Executable name is this
 | It was built with libpng version 1.5.10, and is
 | running with  libpng version 1.5.10 - March 29, 2012

 |    Copyright (C) 1998-2004, 2006-2012 Glenn Randers-Pehrson,
 |    Copyright (C) 1996, 1997 Andreas Dilger,
 |    Copyright (C) 1995, Guy Eric Schalnat, Group 42 Inc.,
 | and zlib version 1.2.6, Copyright (C) 1995-2010 (or later),
 |    Jean-loup Gailly and Mark Adler.
 | It was compiled with gcc version 4.2.1 Compatible Clang 3.0 (tags/RELEASE_30/rc3).

Could not find file: input.png
Could not find file: output.png
   CPU time decoding 0.000, encoding 0.000, other 0.009, total 0.009 seconds
```

I think i´am doing smth. wrong here :D

Sorry for beeing so noobish ;)

Regards
Sebastian

**Comment by richardassar** [comment]
No need to apologise, you're not being noobish.

Just to make sure I understood correctly.

You ran `node pngcrush.js` not pngmin.js as you stated but in the
pngcrush.js that I'd packaged.

The problem is that it's expecting files to exist in the emscripten
virtual file system.

You'd need to make a small wrapper script which loads the files from
disk and then packages them into the emscripten virtual file system
(and then unpacks+saves the resulting output.png once pngcrush is
complete).

See the worker.js file from the project
https://github.com/richardassar/pngcrush.js/blob/master/worker.js

Essentially you just want a version of that, but not for the browser.
You need to call a `FS.createDataFile` to supply your input, followed
by a `getFileData` call (see worker.js).

Thanks,

Richard.

On 29 June 2012 21:39, Sebastian Golasch
reply@reply.github.com
wrote:

**Comment by asciidisco** [comment]
Yap, you got it right.
Thanks for the detailed info, again. Now its working, thanks.

**Comment by richardassar** [comment]
No problem. Glad I could help.
